#!/bin/sh

## Check to see if we are running as root first.

if [ "$(id -u)" != "0" ]; then
    echo "this script must be run as root" 1>&2
    exit 1
fi

echo  "\n============== system init ====================="

echo " * install git"
apt-get install git

set_timezone="cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime"
echo "\n * $set_timezone"

$set_timezone

if [ $? -eq 0 ]
then
	echo " * set_timezone ok"
else
	exit 1
fi

echo "\n * mkdir mount dirs"

mkdir -p /mnt/nanda
mkdir -p /mnt/nandb
mkdir -p /mnt/sd1
mkdir -p /mnt/sd2
mkdir -p /mnt/sda1
mkdir -p /mnt/sd2

if [ $? -eq 0 ]
then
        echo " * mkdir mount dirs ok"
else
        exit 1
fi

echo "\n * start mount sda1 sda2"
mount /dev/sda1 /mnt/sda1

mount /dev/sda2 /mnt/sda2
echo " * start mount sda1 sda2 ok"

echo "\n * install vim"
apt-get install vim

echo "\n * uninstall apache2"
apt-get autoremove --purge apache2
apt-get autoremove --purge apache2-bin
apt-get autoremove --purge apache2-data

echo "\n * install nfs-kernel-server"
apt-get install nfs-kernel-server


echo "\n============== system init end ====================="


