#!/bin/sh

## Check to see if we are running as root first.

if [ "$(id -u)" != "1000" ] ; then
    echo "this script must be run as id eq 1000(linaro)" 1>&2
    exit 1
fi

echo  "\n============== linaro setting init ====================="

user=`whoami`
user_home="/home/$user"


#######################
echo  "\n * mkdir .ssh dir"
if [ -d "$user_home/.ssh" ] ; then
	echo " * not need mkdir -p $user_home/.ssh"
else
	echo " * mkdir -p $user_home/.ssh"
	mkdir -p $user_home/.ssh
fi
echo  "\n * copy .ssh/authorized_keys file"
if [ -f "$user_home/.ssh/authorized_keys" ] ; then
	echo " * not need copy .ssh/authorized_keys"
else
	echo " * cp authorized_keys"
	cp -f .ssh/id_rsa.pub $user_home/.ssh/authorized_keys
fi
chmod 600 $user_home/.ssh/authorized_keys

echo  "\n * copy .ssh/id_rsa.pub file"
if [ -f "$user_home/.ssh/id_rsa.pub" ] ; then
	echo " * not need copy .ssh/id_rsa.pub"
else
	echo " * cp id_rsa.pub"
	cp -f .ssh/id_rsa.pub $user_home/.ssh/id_rsa.pub
fi
chmod 600 $user_home/.ssh/id_rsa.pub

echo  "\n * copy .ssh/id_rsa file"
if [ -f "$user_home/.ssh/id_rsa" ] ; then
	echo " * not need copy .ssh/id_rsa"
else
	echo " * cp id_rsa"
	cp -f .ssh/id_rsa $user_home/.ssh/id_rsa
fi
chmod 600 $user_home/.ssh/id_rsa

echo  "\n * copy .gitconfig file"
if [ -f "$user_home/.gitconfig" ] ; then
	echo " * not need copy .gitconfig"
else
	echo " * cp .gitconfig"
	cp -f .gitconfig $user_home/.gitconfig
fi
chmod 600 $user_home/.gitconfig


#######################
echo "\n * change linaro passwd to ouyangfeng"
if [ "$user" = "linaro" ] ; then
	echo "linaro\nouyangfeng\nouyangfeng\n" | passwd
fi

echo "\n============= linaro setting init end ==================\n"
